import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Generate the player-facing type file Monaco loads for autocomplete.
 *
 * The design requires this be derived from `BotApi` and `ColonyApi` rather than
 * maintained beside them — that is why those are declared as explicit
 * interfaces. `tsc --emitDeclarationOnly` gets us most of the way, including
 * the JSDoc that becomes Monaco's hover text, but its output is a module with
 * imports. Monaco's `addExtraLib` wants one ambient file, so the referenced
 * declarations are inlined and every `export` stripped.
 *
 * Run with `npm run generate:dts`. `tests/editor/dts.test.ts` fails if the
 * committed output drifts from what this produces.
 */

const root = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(root, "src/editor/generated/player-api.d.ts");

/** Pull one `interface Name { ... }` block out by matching braces. */
function extractInterface(source: string, name: string): string {
  const start = source.indexOf(`interface ${name} {`);
  if (start === -1) throw new Error(`no interface ${name} in emitted declarations`);
  let depth = 0;
  for (let i = source.indexOf("{", start); i < source.length; i++) {
    if (source[i] === "{") depth++;
    else if (source[i] === "}" && --depth === 0) return source.slice(start, i + 1);
  }
  throw new Error(`unbalanced braces in interface ${name}`);
}

const stripExports = (s: string): string => s.replace(/^export (declare )?/gm, "");

export function generate(): string {
  const out = mkdtempSync(join(tmpdir(), "automatori-dts-"));
  try {
    // The local tsc entry point, run directly: no npx, and so no shell, which
    // execFileSync warns about on Windows when it is passed arguments.
    execFileSync(process.execPath, [
      join(root, "node_modules/typescript/bin/tsc"),
      "--declaration", "--emitDeclarationOnly", "--noEmit", "false",
      "--outDir", out,
      "--module", "ESNext", "--moduleResolution", "Bundler",
      "--allowImportingTsExtensions", "--target", "ES2022", "--strict",
      join(root, "src/bridge/api.ts"),
    ], { cwd: root, stdio: "pipe" });

    const api = readFileSync(join(out, "bridge/api.d.ts"), "utf8");
    const protocol = readFileSync(join(out, "bridge/protocol.d.ts"), "utf8");
    const simTypes = readFileSync(join(out, "sim/types.d.ts"), "utf8");

    return [
      "// Generated by scripts/generate-dts.ts from src/bridge/api.ts.",
      "// Do not edit by hand: `npm run generate:dts` and commit the result.",
      "",
      "// --- sim vocabulary ---------------------------------------------------",
      stripExports(simTypes).trimEnd(),
      "",
      "// --- a bot's readable state -------------------------------------------",
      stripExports(extractInterface(protocol, "MirrorState")),
      "",
      "// --- what colony.research.status() answers with ------------------------",
      stripExports(extractInterface(protocol, "ResearchStatus")),
      "",
      "// --- the player API ---------------------------------------------------",
      stripExports(extractInterface(api, "BotApi")),
      "",
      stripExports(extractInterface(api, "ColonyApi")),
      "",
      "// Player scripts see these as globals, not as imports.",
      "declare const bot: BotApi;",
      "declare const colony: ColonyApi;",
      "",
    ].join("\n");
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
}

// Only write to disk when run directly, so the test can call generate() alone.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/"))) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, generate(), "utf8");
  console.log(`wrote ${OUT}`);
}
