import type { BlockedOn, Command, Direction, Item, ResearchName, Vec } from "./types.ts";

/*
 * Deliberately not in `types.ts`. The player-facing .d.ts is generated by
 * inlining the whole of that file, so anything living there becomes vocabulary
 * a script author reads in autocomplete. Events are for whatever is drawing the
 * world, and a player script can neither reach them nor do anything with one.
 */
/**
 * Something that happened this tick and has no lasting trace in world state.
 *
 * The sim's own rules do not need these — a refused move simply does not move.
 * They exist because a player watching the world cannot otherwise tell a bot
 * that is working from a bot that is failing over and over, which is the single
 * sharpest thing milestone 3's playtest found.
 *
 * Not history. Drained and discarded, never stored, never in a snapshot, and
 * therefore never part of what determinism compares.
 */
export type WorldEvent =
  // Bots
  | { kind: "bump"; botId: number; pos: Vec; dir: Direction }
  | { kind: "refused"; botId: number; pos: Vec; command: Command["kind"] }
  | { kind: "full"; botId: number; pos: Vec }
  | { kind: "blocked"; botId: number; pos: Vec; on: BlockedOn }
  // Machines. Starved and jammed are opposites and should read as a pair:
  // one wants input it has not got, the other has output it cannot put down.
  | { kind: "starved"; machineId: number; pos: Vec }
  | { kind: "jammed"; machineId: number; pos: Vec }
  | { kind: "research"; name: ResearchName; pos: Vec }
  /**
   * A crop was taken. The only thing here that reports a success.
   *
   * Milestone 7's Task 6, and the only sim edit that task makes. The two other
   * effects it wanted are derivable from the snapshot and are therefore derived
   * rather than announced: a machine appearing is a machine id the renderer has
   * not seen, and a transfer is a bot whose `action` says `deposit` or
   * `withdraw`, which already carries its direction and how much of it is left.
   *
   * A harvest is not, because it leaves nothing behind. The tile simply has no
   * crop, and the only way to notice from outside would be to diff two
   * snapshots — a renderer restating a sim rule, which is what this whole event
   * stream exists to avoid.
   */
  | { kind: "harvest"; botId: number; pos: Vec; item: Item };
