import type { BlockedOn, Command, Direction, ResearchName, Vec } from "./types.ts";

/*
 * Deliberately not in `types.ts`. The player-facing .d.ts is generated by
 * inlining the whole of that file, so anything living there becomes vocabulary
 * a script author reads in autocomplete. Events are for whatever is drawing the
 * world, and a player script can neither reach them nor do anything with one.
 */
/**
 * Something that happened this tick and has no lasting trace in world state.
 *
 * The sim's own rules do not need these — a refused move simply does not move.
 * They exist because a player watching the world cannot otherwise tell a bot
 * that is working from a bot that is failing over and over, which is the single
 * sharpest thing milestone 3's playtest found.
 *
 * Not history. Drained and discarded, never stored, never in a snapshot, and
 * therefore never part of what determinism compares.
 */
export type WorldEvent =
  // Bots
  | { kind: "bump"; botId: number; pos: Vec; dir: Direction }
  | { kind: "refused"; botId: number; pos: Vec; command: Command["kind"] }
  | { kind: "full"; botId: number; pos: Vec }
  | { kind: "blocked"; botId: number; pos: Vec; on: BlockedOn }
  // Machines. Starved and jammed are opposites and should read as a pair:
  // one wants input it has not got, the other has output it cannot put down.
  | { kind: "starved"; machineId: number; pos: Vec }
  | { kind: "jammed"; machineId: number; pos: Vec }
  | { kind: "research"; name: ResearchName; pos: Vec };
